### Matrix product

### [Problem 1] Matrix product is calculated manually

> ref : https://membres-ljk.imag.fr/Bernard.Ycart/mel/cm/node3.html 

In [24]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#c[0,0] = (a[0] * b[:,0]).sum()
#c[0,1] = (a[0] * b[:,1]).sum()
#c[0,2] = (a[0] * b[:,2]).sum()
#c[1,0] = (a[1] * b[:,0]).sum()
#c[1,1] = (a[1] * b[:,1]).sum()
#c[1,2] = (a[1] * b[:,2]).sum()
#c[2,0] = (a[1] * b[:,0]).sum()
#c[2,1] = (a[1] * b[:,1]).sum()
#c[2,2] = (a[1] * b[:,2]).sum()

c = [[(a[0] * b[:,0]).sum(),(a[0] * b[:,1]).sum(), (a[0] * b[:,2]).sum()],
     [(a[1] * b[:,0]).sum(),(a[1] * b[:,1]).sum(), (a[1] * b[:,2]).sum()],
     [(a[2] * b[:,0]).sum(),(a[2] * b[:,1]).sum(), (a[2] * b[:,2]).sum()]]   

print(np.array(c))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


###  [Problème 2】Calcul with NumPy function

In [29]:
#using matmul
import numpy as np
#import numpy.matlib
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
%time print(np.matmul(a,b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 667 µs, sys: 1.16 ms, total: 1.83 ms
Wall time: 2.39 ms


In [28]:
#using dot()
%time print(np.dot(a,b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 957 µs, sys: 1.29 ms, total: 2.24 ms
Wall time: 24.5 ms


In [5]:
#using @ operator
%time print(a@b)

c = a@b
print(c.sum())


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
CPU times: user 587 µs, sys: 185 µs, total: 772 µs
Wall time: 784 µs
0



### [Problem 3] Implementation of calculation of a certain element

Scratch implementation of matrix product
k=0 -> 2 # 2 is the ndarray lenght
∑a(0,k) * b(k,0)

In [45]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
elt = 0
for k in range(len(a)):
    elt += a[0,k] * b[k,0]

print(elt)

6


### [Problem 4] Creating a function that performs matrix multiplication

In [142]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])



def ndarrayProduct(a_ndarray,b_ndarray):
    
    if len(a_ndarray[0])!= len(b_ndarray):
        err_msg = "your two matrix must have same lenght to be mutipliable"
        return err_msg
    
    # if the matrix have the same size the ...
    elt = 0 #matrix elt
    elt_list = [] # list to stock each line mutiliplication
    
    for k in range(len(a_ndarray)):  
        for i in range(len(a_ndarray)):
            elt = 0
            for j in range(len(b_ndarray)):
                elt += (a_ndarray[k,j] * b_ndarray[j,i])  
            elt_list.append(elt)
    new_ndarray = np.array(elt_list).reshape(len(a_ndarray),len(b_ndarray))
    return new_ndarray

print(ndarrayProduct(a,b))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### [Problem 5] Judge the input whose calculation is not defined

In [143]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(ndarrayProduct(d_ndarray,e_ndarray))


your two matrix must have same lenght to be mutipliable


### [Problem 6] Transposition

In [161]:
import numpy as np
a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("using np.transpose()") 
print("(a@b).transpose()") 
print((a@b).transpose())

print("\n")
print("using .T") 
print((a@b).T)


print("\n")
print("transpose of transpose = initial matrix") 
print((a@b).T.T)

using np.transpose()
(a@b).transpose()
[[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]


using .T
[[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]


transpose of transpose = initial matrix
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
