## Problem 1] Number of grains of rice on the 100th day

In [1]:
#importer NumPy
import numpy as np

#creer un tableau simple avec NumPy

sample_ndarray = np.array([1, 2, 3])
print(sample_ndarray)

[1 2 3]


In [2]:
# creer un tableau multidimensionnel
sample_ndarray2 = np.array([[1, 2, 3], [4, 5, 6]])
print(sample_ndarray2)

[[1 2 3]
 [4 5 6]]


## Faire des operation arthmetique sur les tableaux Numpy


In [3]:
#pour ajouter 2 a chaque valeur du tableau
a = 2 
b_list = [1, 2, 3]
c_list = []

for b in b_list:
    c_list.append(a + b)
    
print(c_list)

# les boucles sont tres couteux avec python. Il prennent du temps. Voici pourquoi il faut utiliser Numpy autant que possible

[3, 4, 5]


In [4]:
#pour ajouter 2 a chaque valeur du tableau en utilisant Numpy
print(2 + np.array([1, 2, 3]))

[3 4 5]


In [5]:
# on peut aussi sommer les valeurs d'un tableau de donnee numpy
print(np.array([2, 2, 2]) + np.array([1, 2, 3]))

#on peut aussi faire d'autre operation de la meme maniere
print(np.array([2, 2, 2]) * np.array([1, 2, 3]))

# on peut faire des comparaison entre les valeurs du ndarray
print(np.array([2, 2, 2]) > np.array([1, 2, 3]))


[3 4 5]
[2 4 6]
[ True False False]


In [6]:
# Nous avons donc trois maniere d'ecrire la diffusion de valeurs
print(np.array([2, 2, 2]) + np.array([1, 2, 3]))
print(2 + np.array([1, 2, 3]))
print(np.array([2]) + np.array([1, 2, 3]))

[3 4 5]
[3 4 5]
[3 4 5]


### Les methodes de creation de tableaux

In [7]:
print("creer un tableau np avec la liste") 
sample_ndarray1 = np.array([1, 2, 3])
print(sample_ndarray1)

print("creer un tableau avec un serie de 0 a n") 
# sample_ndarray2 = np.arrange(n)

sample_ndarray2 = np.arange(100)
print(sample_ndarray2)
print(sample_ndarray2.shape)

print("peut aussi s'ecrire ") 
sample_ndarray3 = np.array(range(100))
print(sample_ndarray3)

creer un tableau np avec la liste
[1 2 3]
creer un tableau avec un serie de 0 a n
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)
peut aussi s'ecrire 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
#un tableau ne contenant que des 0 100 fois
sample_array = np.zeros(100)
print(sample_array)
print(sample_array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
(100,)


In [9]:
#un tableau ne contenant que des 1 100 fois
sample_array = np.ones(100)
print(sample_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [10]:
#creer un tableau de 100 valeur ne contenant que des 7 
sample_array = np.full(100, 7)
print(sample_array)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]


In [11]:
sample_ndarray = np.arange(10)
print(sample_ndarray)
print(sample_ndarray[3]) # extraire le troisieme element du tableau
print(sample_ndarray[:3]) # recuperer les 3 premiers valeur
print(sample_ndarray[-1]) # Recuperer le dernier element
print(sample_ndarray[::2]) # recuperer les valeurs du tableau en partant du debut en sautant de deux pas
print(sample_ndarray[::-1]) # renverser le tableau

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2]
9
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [12]:
a_ndarray = np.arange(4)
print(a_ndarray) # un tableau de 0 a 3


print(a_ndarray.shape)#(4,)
print(type(a_ndarray.shape)) #tulpe
b_ndarray = a_ndarray.reshape(2, 2) # disiser le tableau en deux de deux element chacun
print(b_ndarray)
print(b_ndarray.shape) # (2, 2)

[0 1 2 3]
(4,)
<class 'tuple'>
[[0 1]
 [2 3]]
(2, 2)


In [18]:
sample_ndarray = np.arange(6).reshape(2, 3)
sample_ndarray[0, 2] # Extraire les éléments de la ligne 0, colonne 2
sample_ndarray[:, 1:] # Extraire toutes les lignes et colonnes après la première ligne comme un tableau (Sly)

print(sample_ndarray)
print(sample_ndarray[:,0])
#print(sample_ndarray[:, 1:])


[[0 1 2]
 [3 4 5]]
[0 3]


In [14]:
a_ndarray = np.arange(6)
b_ndarray = a_ndarray.reshape(2, 3)
print(a_ndarray)
print(b_ndarray)
print("Le shape est {}".format(b_ndarray.shape)) # (2, 3)
print("La somme est {}".format(b_ndarray.sum())) # 15
print("La somme de l'axe 0 est {}".format(b_ndarray.sum(axis=0))) # [3 5 7]
print("La somme de l'axe 1 est {}".format(b_ndarray.sum(axis=1))) # [3 5 7]
print("la moyenne de l'axe 1 est {}".format(b_ndarray.mean(axis=1))) # [1. 4.]

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
Le shape est (2, 3)
La somme est 15
La somme de l'axe 0 est [3 5 7]
La somme de l'axe 1 est [ 3 12]
la moyenne de l'axe 1 est [1. 4.]
