### SAMPLE CODE

In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("average :", scaler.mean_)
print("Var :", scaler.var_)
X_std = scaler.transform(X)

average : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]


## [Problem 1] Enumeration of classes used so far


1- sklearn.model_selection

2- pandas.DataFrame()

3- matplotlib.pyplot


## [Problem 2] Enumeration of methods and instance variables used so far


### method

1- numpy.sum() : calculer la somme des colonnes d'un Ndarray

2- numpy.mean() : calculer la moyennes des colonne d'un Ndarray

3- numpy.append() : ajouter des elements a un array

4- pandas.DataFrame.loc() : selection par indexation basee sur le lables de la colonne

5- pandas.DataFrame.head() : returne n premieres ligne d'un DataFrame


### Instance variable 

1- ndarray.shape : retourn les dimension d'un ndarry (nombre de ligne et nombre de colonnes)

2- ndarray.size : retourn la taille d'un ndarry 

3- ndarray.dtype : retourne le type des element d'un ndarry

3- pandas.DataFrame.columns : return les noms de colonnes d'un dataframe

4- pandas.DataFrame.index : return les indexs d'un dataframe





## [Problem 3] Creating a standardized class by scratch

In [79]:
class ScratchStandardScaler():
    """
    Classes for standardization
    Attributes
    ----------
    mean_ : ndarray of the following form, shape(n_features,)
        average
    var_ : ndarray of the following form, shape(n_features,)
        distribution
    """
    def fit(self, X):
        """
        Calculate the AVERAGE and standard deviation for standardization.。
        Parameters
        ----------
        X : ndarray of the following form, shape (n_samples, n_features)
            Training data
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        Standardize using the values obtained by fit.。
        Parameters
        ----------
        X : ndarray of the following form, shape (n_samples, n_features)
            Feature value
        Returns
        ----------
        X_scaled : ndarray of the following form, shape (n_samples, n_features)
            Standardized feature values
        """
        X_scaled = (X - self.mean_)/self.var_
        pass
        return X_scaled

**A noter :  Comment standardiser une matrix?**

https://stackoverflow.com/questions/4544292/how-do-i-standardize-a-matrix/4544459
Ce qui suit soustrait la moyenne de A de chaque élément (la nouvelle moyenne est 0), puis normalise le résultat par l'écart type.

`import numpy as np
A = (A - np.mean(A)) / np.std(A)`

Ce qui précède sert à normaliser l'ensemble de la matrice dans son ensemble, si A a plusieurs dimensions et que vous souhaitez normaliser chaque colonne individuellement, spécifiez l' axe :

`import numpy as np
A = (A - np.mean(A, axis=0)) / np.std(A, axis=0)`
Vérifiez toujours à la main ce que font ces one-liners avant de les intégrer dans votre code. Un simple changement d'orientation ou de dimension peut changer radicalement (silencieusement) les opérations que numpy effectue sur eux.

- ### Let's make the following code executable.

In [80]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("average : {}".format(scratch_scaler.mean_))
print("distribution : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print("X_std : {}".format(X_std))

average : [4.86 3.31 1.45 0.22]
distribution : [0.0764 0.0849 0.0105 0.0056]
X_std : [[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


# [Problem 4] Creating a class that performs 4 arithmetic operations

In [75]:
def CatchValueError(value):
    try:
        int(value)
        return False
    except ValueError:
        return True

 
    
class Perform():
    """
    A simple class for illustration
    Parameters
    ----------
    value : float or int
        Initial value
    Attributes
    ----------
    value : float or int
        Initial calculation results
    """
    def __init__(self, value):
        if CatchValueError(value):
            print("Oops! The initial value is no valid number.  Try again...")
        else:
            self.value = value
            print("The initial value {} has been set.".format(self.value))
    
    
    def add(self, value2):
        """
        Add the received arguments to self.value
        """
        if CatchValueError(value2):
            print("Oops! the second value is no valid number.  Try again...")
        else:
            self.value += value2
            
    
    def multiply(self, value3):
        """
        multiply the received arguments to self.value
        """
        if CatchValueError(value3):
            print("Oops! the second value is no valid number.  Try again...")
        else:
            self.value = self.value * value3
    
    def soustract(self, value4):
        """
        soustrct the received arguments to self.value
        """
        if CatchValueError(value4):
            print("Oops! the second value is no valid number.  Try again...")
        else:
            self.value -= value4
        
    def divise(self, value4):
        """
        soustrct the received arguments to self.value
        """
        if CatchValueError(value4):
            print("Oops! the second value is no valid number.  Try again...")
        else:
            try:
                self.value = self.value / value4
                return self.value
            except ZeroDivisionError:
                print("Oops! you can divise by 0. Try agrain ... ")
                



In [63]:
print("expected error")
example = Perform("K")

expected error
Oops! The initial value is no valid number.  Try again...


In [64]:
print("expected error")
example = Perform(5)
example.multiply("n")

expected error
The initial value 5 has been set.
Oops! the second value is no valid number.  Try again...


In [78]:
print("Multiplication")  
example = Perform(5)
example.multiply(3)
print("value : {}".format(example.value))

Multiplication
The initial value 5 has been set.
value : 15


In [70]:
print("soustraction")
example = Perform(8)
example.soustract(3)
print("value : {}".format(example.value))


soustraction
The initial value 8 has been set.
value : 5


In [72]:
print("addition")  
example = Perform(5)
example.add(3)
print("value : {}".format(example.value))


addition
The initial value 5 has been set.
value : 8


In [76]:
print("division error")  
example = Perform(5)
example.divise(0)

division error
The initial value 5 has been set.
Oops! you can divise by o 


In [77]:
print("division")  
example = Perform(10)
example.divise(2)
print("value : {}".format(example.value))

division
The initial value 10 has been set.
value : 5.0
